### ISSUE TITLE
Can not support one yaml format

### ISSUE THREAD

**Issue by mizeng** [fabiocaccamo/python-benedict#50]
```yaml
apiVersion: v1
data:
  filebeat.yml: |-
```

if my yaml is as above,  ` benedict.from_yaml` will throw exception 
```
Traceback (most recent call last):
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/yaml_handle/process_yaml1.py", line 13, in <module>
    d = benedict.from_yaml(f)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/dicts/io/io_dict.py", line 150, in from_yaml
    return cls(s, format='yaml', **kwargs)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/dicts/__init__.py", line 44, in __init__
    super(benedict, self).__init__(*args, **kwargs)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/dicts/keypath/keypath_dict.py", line 16, in __init__
    keypath_util.check_keys(self, self._keypath_separator)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/dicts/keypath/keypath_util.py", line 24, in check_keys
    traverse(d, check_key)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/core/traverse.py", line 31, in traverse
    _traverse_collection(d, callback)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/core/traverse.py", line 8, in _traverse_collection
    _traverse_dict(d, callback)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/core/traverse.py", line 18, in _traverse_dict
    _traverse_collection(value, callback)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/core/traverse.py", line 8, in _traverse_collection
    _traverse_dict(d, callback)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/core/traverse.py", line 17, in _traverse_dict
    callback(d, key, value)
  File "/Users/mizeng/Projects/PycharmProjects/Ming/tools/.venv/lib/python3.7/site-packages/benedict/dicts/keypath/keypath_util.py", line 23, in check_key
    '\'{}\', found: \'{}\'.'.format(separator, key))
ValueError: keys should not contain keypath separator '.', found: 'filebeat.yml'.

```

**Comment by fabiocaccamo** [comment]
@mizeng if you initialize `benedict` from an other dict or from a data source, the existing keys **must not contain** the separator. 

`.` is the default `keypath_separator`, you can [use a custom one](https://github.com/fabiocaccamo/python-benedict#custom-keypath-separator) or [disable it](https://github.com/fabiocaccamo/python-benedict#disable-keypath-functionality) at all:
```python
b = benedict.from_yaml('yourfile.yml', keypath_separator='/')
```
